# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zak Kolar
name: Zak Kolar

description: "Zak Kolar is a Digital Learning Teacher in Waltham, MA. He works with students and teachers to incorporate digital literacy."
url: ""

twitter:
  username: "ZakKolar"

title_separator: "|"



author:
  name: "Zak Kolar"
  avatar: "/assets/images/zak-cartoon.png"
  bio: "Digital Learning Teacher in Waltham, Massachusetts"
  links:
  - label: "All posts"
    icon: "fas fa-fw fa-book"
    url: "/archive/"
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/ZakKolar"
  - label: "Youtube"
    icon: "fab fa-fw fa-youtube"
    url: "https://www.youtube.com/channel/UCAp2oZm0CGRtb2U4g9V3OQA"
  - label: "Linkedin"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/zakkolar/"
  - label: "Github"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/ZakKolar"

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ZakKolar"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCAp2oZm0CGRtb2U4g9V3OQA"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/zakkolar/"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ZakKolar"


search: true
search_provider: algolia

algolia:
  application_id: 03UNUT396P
  index_name: dev_zak.io
  search_only_api_key: 2226afc7e62cdfd9d31cfd1b392706af
  powered_by: true
  files_to_exclude:
    - _pages/policy-cookie.md
    - _pages/addon-terms-of-service.md


default_color: "#34495e"

defaults:
# _pages
- scope:
    path: ""
    type: pages
  values:
    layout: single
    author_profile: false
    header:
      color: "#34495e"
      teaser: "/assets/images/zak-cartoon.png"
# _posts
- scope:
    path: ""
    type: posts
  values:
    permalink: /post/:year/:month/:day/:title/
    layout: single
    comments: # true
    related: true
    show_subscribe: true
    author_profile: false
    header:
      color: "#34495e"
- scope:
    path: "admin"
  values:
    sitemap: false
    # _portfolio
- scope:
    path: ""
    type: projects
  values:
    permalink: /portfolio/programming/:slug/
    layout: project
    author_profile: false
    share: false
    header:
      color: "#34495e"

- scope:
    path: ""
    type: addons
  values:
    permalink: /addon/:slug/
    layout: project
    author_profile: false
    share: false
    header:
      color: "#34495e"


collections:
  projects:
    output: true
    permalink: /:collection/:path/
  addons:
    output: true
    permalink: /:collection/:path/


srcset:
  cache: "/tmp/images"

sass:
  style: compressed
jekyll_compose:
  post_default_front_matter:
    excerpt:
    image:
    header:
      color: ''
      image:
      image_description:
      teaser:
      actions:
      - url:
        label:
    categories:
    tags:

#paginate: 5 # amount of posts to show
#paginate_path: /page:num/

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-srcset


include: ["_pages", "_redirects", "robots.txt"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - package.json
   - package-lock.json
   - banner.js